# Generated by Django 3.0.3 on 2020-02-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('I_nita_baker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.TextField(blank=True, default=''),
        ),
    ]
